WebAppAsesorias/Models/ClasificacionPeticionModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebAppAsesorias.Models
{
    public class ClasificacionPeticionModel
    {
        public int Id { get; set; }
        public string? TextoAyuda { get; set; }
        public string? DescTipoPeticion { get; set; }
        public List<SelectListItem>? ListaAreaDerecho { get; set; } 
        public List<ParametrosModel> Derechos { get; set; } = new List<ParametrosModel>();
        public string? DescripcionAsesorias { get; set; }
        public string? Observaciones { get; set; }
        public bool RespuestaAsesoria { get; set; }
        public string? ConclusionAsesoria { get; set; }
    }
}

WebAppAsesorias/Models/DerechoModel.cs
namespace WebAppAsesorias.Models
{
    public class DerechoModel
    {
        public int IdDerecho { get; set; }
        public string? DescDerecho { get; set; }
    }

}

WebAppAsesorias/Models/ErrorViewModel.cs
namespace WebAppAsesorias.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebAppAsesorias/Models/ParametrosModel.cs
namespace WebAppAsesorias.Models
{
    public class ParametrosModel
    {
        public int IdParametro { get; set; }
        public string? DescParametro { get; set; }
    }

}

WebAppAsesorias/Controllers/ClasificacionPeticionController.cs
using Logica;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebAppAsesorias.Models;

namespace WebAppAsesorias.Controllers
{
    public class ClasificacionPeticionController : Controller
    {
        // GET: ClasificacionPeticionController
        public ActionResult Index()
        {
          return View();
        }
        
        // GET: ClasificacionPeticionController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ClasificacionPeticionController/Create
        public ActionResult Radicar()
        {
            ClasificacionPeticionLogica clasificacionPeticionLogica = new ClasificacionPeticionLogica();
           // clasificacionPeticionLogica.Radicar("","",);
            return View();
        }

        // POST: ClasificacionPeticionController/Create
        [HttpPost]
//        [ValidateAntiForgeryToken]
        public ActionResult RadicarPeticion(ClasificacionPeticionModel clasificacionPeticionModel)
        {
            try
            {
                var clasificacionPeticionLogica = new ClasificacionPeticionLogica();
                var respuesta = clasificacionPeticionLogica.RadicarPeticion("1", "1", "1", clasificacionPeticionModel.ConclusionAsesoria, clasificacionPeticionModel.Observaciones, "jahc");

                return RedirectToAction(nameof(RegistroDePeticionarios));
            }
            catch
            {
                return View();
            }
        }

        // GET: ClasificacionPeticionController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ClasificacionPeticionController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ClasificacionPeticionController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ClasificacionPeticionController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        //[HttpGet]
        public ActionResult RegistroDePeticionarios()
        {

            ParametroLogica parametroLogica = new ParametroLogica();
            var listaParametros = parametroLogica.ConsultarParametrosXCodTipo("AREADERE");

            ClasificacionPeticionModel data = new ClasificacionPeticionModel(); 
            data.DescTipoPeticion = "";

            data.ListaAreaDerecho = new List<SelectListItem>();

            foreach (var item in listaParametros)
            {
                var itemDerecho = new SelectListItem { Text = item.Descripcion, Value = item.Codigo};
                data.ListaAreaDerecho.Add(itemDerecho);
            }

            data.Derechos = new List<ParametrosModel>();
            data.DescripcionAsesorias = "";
            data.Observaciones = "";
            data.RespuestaAsesoria = false;
            data.ConclusionAsesoria = "";
            return View(data);
        }
    }
}

WebAppAsesorias/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebAppAsesorias.Models;

namespace WebAppAsesorias.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebAppAsesorias/Views/ClasificacionPeticion/RegistroDePeticionarios.cshtml
@model WebAppAsesorias.Models.ClasificacionPeticionModel
<!DOCTYPE html>
<html>
<head>
    <!--<link rel="stylesheet" href="~/css/FontAwesome.css" asp-append-version="true" />-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="~/css/Ultimus.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/toastr.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/font-awesome.css" asp-append-version="true" />
    <title>Formulario de Asesoría</title>

    <style>
        .help-text {
            background-color: #f9f9f9;
            border: 1px solid #c0c0c0;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 10px;
        }

        .form-row {
            display: flex;
            margin-bottom: 10px;
            align-items: center;
        }

            .form-row label {
                width: 180px;
                margin-right: 10px;
            }

            .form-row input[type="text"],
            .form-row select,
            .form-row textarea {
                flex: 1;
                padding: 5px;
            }

            .form-row input[type="submit"] {
                width: auto;
                margin: 20px 0;
                cursor: pointer;
            }

        .form-row {
            display: flex;
            margin-bottom: 10px;
            align-items: center;
        }

            .form-row label {
                width: 180px;
                margin-right: 10px;
            }

            .form-row input[type="text"],
            .form-row select,
            .form-row textarea {
                flex: 1;
                padding: 5px;
            }

            .form-row input[type="submit"] {
                width: auto;
                margin: 20px 0;
                cursor: pointer;
            }
    </style>
</head>
<body>
    <form method="post">
        <div class="button-container">
            <button class="btn amarillo"><i class="fas fa-print"></i> Imprimir Pantalla</button>
            <button class="btn verde" type="submit" asp-controller="ClasificacionPeticion" asp-action="RadicarPeticion"><i class="fas fa-save"></i> Guardar/Radicar</button>
            <button class="btn amarillo"><i class="fas fa-sync-alt"></i> Ver trámite</button>
            <button class="btn gris"><i class="fas fa-eye"></i> Ver etiqueta</button>
            <button class="btn rojo"><i class="fas fa-circle"></i> Enviar</button>
        </div>

        <div class="help-text">
            ASESORÍA: La asesoría consiste en orientar al peticionario en el ejercicio y defensa de los derechos humanos, ante las autoridades competentes o ante las entidades de carácter privado.
        </div>
        <div class="form-row">
            <label for="tipoPeticion">Tipo de petición:</label>
            <input type="text" id="tipoPeticion" name="tipoPeticion" value="@Model.DescTipoPeticion">
            <span class="input-group-btn">
                <button type="button" class="btn btn-default btn-medium">
                    <i class="fa fa-close"></i>
                </button>
                <button type="button" class="btn btn-success btn-medium btn-margin-catalogo btn-file" usehttppost="0" webapplication="" usedatasource="0">
                    <i class="fa fa-search"></i>&nbsp;
                </button>

            </span>
            <style>
                .form-row {
                    display: flex;
                    align-items: center;
                    justify-content: space-between;
                }

                    .form-row label {
                        margin-right: 10px;
                    }

                    .form-row input[type="text"] {
                        flex-grow: 1;
                        margin-right: 10px;
                    }

                .input-group-btn {
                    display: flex;
                }

                .btn-medium {
                    padding: 0.5rem 0.75rem;
                }

                .btn-margin-catalogo {
                    margin-right: 5px;
                }
            </style>
        </div>

        <div class="form-row">
            <label for="areaDerecho">Área de derecho:</label>
            @Html.DropDownListFor(model => model.ListaAreaDerecho, Model.ListaAreaDerecho, "-- Seleccione un valor --")
        </div>

        <div class="form-row">
            <label for="derechos">Derechos:</label>
            <input type="text" id="derechos" name="derechos">
            <span class="input-group-btn">
                <button type="button" class="btn btn-default btn-medium">
                    <i class="fa fa-close"></i>
                </button>
                <button type="button" class="btn btn-success btn-medium btn-margin-catalogo btn-file" usehttppost="0" webapplication="" usedatasource="0">
                    <i class="fa fa-search"></i>&nbsp;
                </button>
            </span>
            <style>
                .form-row {
                    display: flex;
                    align-items: center;
                    justify-content: space-between;
                }

                    .form-row label {
                        margin-right: 10px;
                    }

                    .form-row input[type="text"] {
                        flex-grow: 1;
                        margin-right: 10px;
                    }

                .input-group-btn {
                    display: flex;
                }

                .btn-medium {
                    padding: 0.5rem 0.75rem;
                }

                .btn-margin-catalogo {
                    margin-right: 5px;
                }
            </style>
        </div>

        <div class="form-row">
            <label for="descripcionAsesoria">Descripción de asesoría:</label>
            <textarea id="descripcionAsesoria" name="descripcionAsesoria"></textarea>
        </div>

        <div class="form-row">
            <label for="observaciones">Observaciones:</label>
            <textarea id="observaciones" name="observaciones">@Model.Observaciones</textarea>
        </div>



        <div class="form-row">
            <label>¿La asesoría debe generar respuesta por escrito?</label>
            <div class="radio-group">
                <div>
                    <input type="radio" id="respuestaEscritaSi" name="respuestaEscrita" value="si" onclick="OcultarConclusiones()">
                    <label for="respuestaEscritaSi">Sí</label>
                </div>
                <div>
                    <input type="radio" id="respuestaEscritaNo" name="respuestaEscrita" value="no" onclick="OcultarConclusiones()">
                    <label for="respuestaEscritaNo">No</label>
                </div>
            </div>
        </div>



        <div class="form-row" id="divConclusionAsesoria">
            <label class="control-label col-sm-4" for="conclusionAsesoria">Conclusión de asesoría:</label>
            <textarea id="txtConclusionAsesoria" name="conclusionAsesoria">@Model.ConclusionAsesoria</textarea>
            &nbsp;&nbsp;&nbsp;&nbsp;

            <span class="input-group-btn">
                <button type="button" id="btnLimpiarConclusionAsesoria" onclick="LimpiarConclusionesAsesorias()" class="btn btn-default btn-medium">
                    <i class="fa fa-close"></i>
                </button>
                <button type="button" id="btnBuscarConclusionAsesoria" class="btn btn-success btn-medium btn-margin-catalogo btn-file" usehttppost="0" webapplication="" usedatasource="0">
                    <i class="fa fa-search"></i>&nbsp;
                </button>
            </span>
            <style>
                .form-row {
                    display: flex;
                    align-items: center;
                    justify-content: space-between;
                }

                    .form-row label {
                        margin-right: 10px;
                    }

                    .form-row input[type="text"] {
                        flex-grow: 1;
                        margin-right: 10px;
                    }

                .input-group-btn {
                    display: flex;
                }

                .btn-medium {
                    padding: 0.5rem 0.75rem;
                }

                .btn-margin-catalogo {
                    margin-right: 5px;
                }
            </style>
        </div>


    </form>
</body>
</html>

WebAppAsesorias/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Defensoría de Pueblo";
}

<div class="text-center">
    
    <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
            Asesorías
        </li>
        <li class="nav-item">
            Quejas
        </li>
        <li class="nav-item">
            Solicitudes
        </li>
    </ul>
    
</div>